### ISSUE TITLE
Error when running the HbaseApplication

### ISSUE THREAD

**Issue by zhipingwu** [tspannhw/phoenix#2]
```
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
	at org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.build(Jackson2ObjectMapperBuilder.java:588) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.<init>(MappingJackson2HttpMessageConverter.java:57) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.social.oauth1.AbstractOAuth1ApiBinding.getJsonMessageConverter(AbstractOAuth1ApiBinding.java:158) ~[spring-social-core-1.1.4.RELEASE.jar:1.1.4.RELEASE]
	at org.springframework.social.twitter.api.impl.TwitterTemplate.getJsonMessageConverter(TwitterTemplate.java:162) ~[spring-social-twitter-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at org.springframework.social.oauth1.AbstractOAuth1ApiBinding.getMessageConverters(AbstractOAuth1ApiBinding.java:126) ~[spring-social-core-1.1.4.RELEASE.jar:1.1.4.RELEASE]
	at org.springframework.social.oauth1.AbstractOAuth1ApiBinding.createRestTemplateWithCulledMessageConverters(AbstractOAuth1ApiBinding.java:217) ~[spring-social-core-1.1.4.RELEASE.jar:1.1.4.RELEASE]
	at org.springframework.social.oauth1.AbstractOAuth1ApiBinding.createRestTemplate(AbstractOAuth1ApiBinding.java:175) ~[spring-social-core-1.1.4.RELEASE.jar:1.1.4.RELEASE]
	at org.springframework.social.oauth1.AbstractOAuth1ApiBinding.<init>(AbstractOAuth1ApiBinding.java:71) ~[spring-social-core-1.1.4.RELEASE.jar:1.1.4.RELEASE]
	at org.springframework.social.twitter.api.impl.TwitterTemplate.<init>(TwitterTemplate.java:79) ~[spring-social-twitter-1.1.2.RELEASE.jar:1.1.2.RELEASE]
	at com.dataflowdeveloper.HBaseApplication$LocalConfiguration.twitter(HBaseApplication.java:50) ~[classes/:na]
	at com.dataflowdeveloper.HBaseApplication$LocalConfiguration$$EnhancerBySpringCGLIB$$e3f89c27.CGLIB$twitter$1(<generated>) ~[classes/:na]
	at com.dataflowdeveloper.HBaseApplication$LocalConfiguration$$EnhancerBySpringCGLIB$$e3f89c27$$FastClassBySpringCGLIB$$4e77db79.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at com.dataflowdeveloper.HBaseApplication$LocalConfiguration$$EnhancerBySpringCGLIB$$e3f89c27.twitter(<generated>) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	... 47 common frames omitted

2019-12-28 18:36:43.757  INFO 18804 --- [      Thread-14] nectionManager$HConnectionImplementation : Closing zookeeper sessionid=0x6e9cbc63430c1d
```

**Comment by zhipingwu** [comment]
error still exists through i imported jackson databind .
